### ISSUE TITLE
请问这个框架有经历线上环境验证了吗？

### ISSUE THREAD

**Issue by lubaoyilang** [woodylan/go-websocket#1]
我可以直接在我们项目中使用吗？
websocket的 心跳等框架层有吗？还是需要我 在业务层自己实现？

**Comment by woodylan** [comment]
可以直接使用，也加了心跳，心跳那个参数用常量的方式写在代码上了，你可以改数值。

**Comment by lubaoyilang** [comment]
如果我需要监控 客户端上下线的消息，是不是目前不支持 ws主动给 业务 推送消息？
只能业务服务器根据 clientid 来调用ws服务器？

**Comment by woodylan** [comment]
转变一下思路，把业务当做客户端，这样就可以给业务推送消息了。

**Comment by lubaoyilang** [comment]
你这个框架太棒了，veryGood
我是做客户端的，后端长链需要一个服务，一直在想，接第三方还是自己搭建。。
Golang好多这种类似的长连接服务，太不成熟。
希望你可以维护下去，感谢。

**Comment by woodylan** [comment]
谢谢，我会一直维护下去。也希望有问题或者建议可以反馈给我。

**Comment by qyvlik** [comment]
@woodylan 可以多写一些测试用例，测试用例写得准确，覆盖较为完整，可以提升项目的质量。

**Comment by woodylan** [comment]
> @woodylan 可以多写一些测试用例，测试用例写得准确，覆盖较为完整，可以提升项目的质量。

嗯嗯，纳入接下来的计划中。
