### ISSUE TITLE
manager.ClientIdMap设计有问题

### ISSUE THREAD

**Issue by sawyerRick** [woodylan/go-websocket#9]
manager.ClientIdMap的key clientId只是服务器的ip:port，如果新ws连接使用的ip:port相同则会覆盖旧key。结果：无法取得被覆盖的conn。
如果我理解错了，请让我知道，谢谢。

**Comment by woodylan** [comment]
key采用利用对称加密，每一次加密的结果都不一样，所以不会覆盖掉旧的。

**Comment by sawyerRick** [comment]
感谢回复，我明白了，代码中使用rand.Reader初始化了aes的iv。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月12日(周一) 晚上10:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [woodylan/go-websocket] manager.ClientIdMap设计有问题 (#9)




 
key采用利用对称加密，每一次加密的结果都不一样，所以不会覆盖掉旧的。
